//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.05 at 11:14:13 AM CEST 
//


package basic.zKernel.html.classes.ventian;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the basic.zKernel.html.classes.ventian package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tabledata_QNAME = new QName("", "tabledata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: basic.zKernel.html.classes.ventian
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TabledataType }
     * 
     */
    public TabledataType createTabledataType() {
        return new TabledataType();
    }

    /**
     * Create an instance of {@link RowType }
     * 
     */
    public RowType createRowType() {
        return new RowType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TabledataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tabledata")
    public JAXBElement<TabledataType> createTabledata(TabledataType value) {
        return new JAXBElement<TabledataType>(_Tabledata_QNAME, TabledataType.class, null, value);
    }

}
